// Generated by CoffeeScript 1.9.3
(function() {
  $(".errors li").hide();

  $("form").submit(function() {
    var pass, text;
    $(".errors li").hide();
    text = $("input[type='text']").val();
    pass = $("input[type='password']").val();
    if (!text.match(/.*@.*\..*/)) {
      $(".errors li:nth-child(1)").show();
    }
    if (pass.length < 8) {
      $(".errors li:nth-child(2)").show();
    }
    if (!pass.match(/.*[A-Z].*/)) {
      $(".errors li:nth-child(3)").show();
    }
    if (!pass.match(/.*[0-9].*/)) {
      return $(".errors li:nth-child(4)").show();
    }
  });

}).call(this);
