// Generated by CoffeeScript 1.12.6
(function() {
  var Validator, email, err, pass, v;

  Validator = (function() {
    function Validator(emailSel, passSel, errSel) {
      this.emailSel = emailSel;
      this.passSel = passSel;
      this.errSel = errSel;
      this.emailRegex = /^([a-zA-Z0-9!#$%&'*\+\-\/=?^_`{|}~]+(?:\.*[a-zA-Z0-9!#$%&'*\+\-\/=?^_`{|}~]+)*)@([a-zA-Z0-9\-]+(?:\.[a-zA-Z0-9\-]+)+)$/;
      this.upperCaseRegex = /.*[A-Z]+.*/;
      this.digitRegex = /.*[0-9]+.*/;
    }

    Validator.prototype.check = function() {
      $(this.errSel).empty();
      return this.checkEmail() && this.checkPassword();
    };

    Validator.prototype.checkEmail = function() {
      var s;
      s = $(this.emailSel).val();
      if (!this.emailRegex.test(s)) {
        $(this.errSel).append('<li>Please enter a valid email address</li>');
        return false;
      } else {
        return true;
      }
    };

    Validator.prototype.checkPassword = function() {
      var s, valid;
      s = $(this.passSel).val();
      valid = true;
      if (s.length < 8) {
        $(this.errSel).append('<li>Your password should be at least 8 characters long</li>');
        valid = false;
      }
      if (!this.upperCaseRegex.test(s)) {
        $(this.errSel).append('<li>Your password should contain at least one capital letter</li>');
        valid = false;
      }
      if (!this.digitRegex.test(s)) {
        $(this.errSel).append('<li>Your password should contain at least one number (0-9)</li>');
        valid = false;
      }
      return valid;
    };

    return Validator;

  })();

  email = 'input[type=text]';

  pass = 'input[type=password]';

  err = 'ul.errors';

  $(err).empty();

  v = new Validator(email, pass, err);

  $('input[type=submit]').click(function(e) {
    if (!v.check()) {
      e.preventDefault();
    } else {
      $('form').submit();
      alert('Sign in successful!');
    }
    return null;
  });

}).call(this);
