// Generated by CoffeeScript 1.10.0
(function() {
  var form, validateEmail, validatePassword;

  form = document.forms["sign_in"];

  $(document).ready(function() {
    $(".errors").children().hide();
    return $("form").submit(function() {
      validateEmail();
      validatePassword();
    });
  });

  validateEmail = function() {
    var email;
    email = /(^[a-z0-9_])+(.|[_])*([a-z0-9])*@([a-z]+).+/;
    validateEmail = form.elements[0].value;
    if (validateEmail === null || validateEmail === "") {
      $(".errors li:nth-child(1)").show();
    }
    if (!email) {
      $(".errors li:nth-child(1)").show();
    }
  };

  validatePassword = function() {
    var hasDigit, hasUpper, password;
    password = form.elements[1].value;
    hasDigit = /[0-9]/.test(password);
    hasUpper = /[A-Z]/.test(password);
    if (password === null || password === "") {
      $(".errors li:nth-child(2)").show();
      $(".errors li:nth-child(3)").show();
      $(".errors li:nth-child(4)").show();
    }
    if (password.length < 8) {
      $(".errors li:nth-child(2)").show();
    }
    if (!hasUpper) {
      $(".errors li:nth-child(3)").show();
    }
    if (!hasDigit) {
      $(".errors li:nth-child(4)").show();
    }
  };

}).call(this);
