// Generated by CoffeeScript 1.10.0
(function() {
  var email_field, error_display, error_hide, error_list, form, pwd_field, submit_button;

  error_display = function(el) {
    return el.css('display', 'auto');
  };

  error_hide = function(el) {
    return el.css('display', 'none');
  };

  form = $('form[name="sign_in"]');

  email_field = form.children().eq(0);

  pwd_field = form.children().eq(2);

  submit_button = $('input[type="submit"]');

  error_list = $('.errors').children();

  error_hide(error_list);

  $(function() {
    form.submit(function() {
      var conditions, email, email_regex, i, j, len, len1, pwd, x;
      email = email_field.val();
      pwd = pwd_field.val();
      email_regex = /^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i;
      conditions = [
        {
          condition: (email.match(email_regex)) !== null,
          error_no: 0
        }, {
          condition: pwd.length >= 8,
          error_no: 1
        }, {
          condition: (pwd.match(/[A-Z]/)) !== null,
          error_no: 2
        }, {
          condition: (pwd.match(/\d/)) !== null,
          error_no: 3
        }
      ];
      console.log(conditions);
      for (i = 0, len = conditions.length; i < len; i++) {
        x = conditions[i];
        error_hide(error_list.eq(x.error_no));
      }
      for (j = 0, len1 = conditions.length; j < len1; j++) {
        x = conditions[j];
        if (x.condition) {
          error_hide(error_list.eq(x.error_no));
        } else {
          error_display(error_list.eq(x.error_no));
        }
      }
      if (conditions.every(function(el) {
        return el.condition === true;
      })) {
        return alert("Success");
      }
    });
    return true;
  });

}).call(this);
