// Generated by CoffeeScript 1.12.6
(function() {
  var checkEmail, checkPassword;

  $(document).ready(function() {
    return $('.errors').children().hide();
  });

  $('input[type="submit"').click(function(e) {
    var emailValid, passwordValid;
    e.preventDefault();
    $('.errors').children().hide();
    emailValid = checkEmail($('[placeholder="Email"]').val());
    passwordValid = checkPassword($('[placeholder="Password"]').val());
    if (emailValid && passwordValid) {
      $('form').submit();
      return alert('Form submitted');
    }
  });

  checkEmail = function(input) {
    if (!/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/g.test(input)) {
      $('.errors li:nth-child(1)').show();
      return false;
    } else {
      return true;
    }
  };

  checkPassword = function(input) {
    if (!/^(?=.*\d)(?=.*[A-Z]).{8,}$/g.test(input)) {
      $('.errors li:nth-child(2), .errors li:nth-child(3), .errors li:nth-child(4)').show();
      return false;
    } else {
      return true;
    }
  };

}).call(this);
